name: paynow

description: Paynow Client helper package to help initiate payments.
version: 3.0.2

email: iamsupercode@outlook.com
homepage: https://github.com/ignertic/paynow

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.2
  crypto: ^3.0.1
  intl: ^0.18.1
  localregex: '>=4.0.5'



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: